### ISSUE TITLE
Discord logo only shows half of the logo

### ISSUE THREAD

**Issue by hgoona** [shinokada/svelte-supertiny#1]
### Describe the bug

Discord logo only shows half of the logo when used in SvelteKit as <Discord />: 
![image](https://github.com/shinokada/svelte-supertiny/assets/30910108/c0898516-e56c-4c96-9110-b12b047788ed)

### Reproduction

Using as:
```
<script> 
import Discord from "svelte-supertiny/Discord.svelte";
</script> 

<Discord />
```

### Version and System Info

```shell
System:
    OS: Windows 10 
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220918.223204.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
  Browsers:
    Chrome: 126.0.6478.114
  npmPackages:
    @sveltejs/kit: ^2.5.10 => 2.5.10
    svelte: ^4.2.15 => 4.2.15
    svelte-supertiny: ^1.0.4 => 1.0.4
    vite: ^5.2.10 => 5.2.10
```

**Comment by shinokada** [comment]
A new version is released. 

```
pnpm i -D svelte-supertiny@latest
```

**Comment by hgoona** [comment]
> A new version is released.
> 
> ```
> pnpm i -D svelte-supertiny@latest
> ```

I ended up finding the bug and made a duplicate svg😅 Amazing! Super fast - thank you💪🏾💪🏾💪🏾

**Comment by hgoona** [comment]
Actually, @shinokada im not seeing the change in the updated pkg. 
This was the fix I did on my local: inside the transform of the SVG:
![image](https://github.com/shinokada/svelte-supertiny/assets/30910108/9fb1445a-7b8d-4752-ae27-b5573cfef938)

**Comment by shinokada** [comment]
![image](https://github.com/shinokada/svelte-supertiny/assets/147320/93bedf3e-febc-41cd-9feb-6fbe4b10a64f)

As you see on the website, it should be fixed. https://svelte-supertiny.codewithshin.com/icons

**Comment by hgoona** [comment]
@shinokada For some reason if i scroll down to the Discord logo on your page: https://svelte-supertiny.codewithshin.com/icons i see this>>>
![image](https://github.com/shinokada/svelte-supertiny/assets/30910108/5cb97699-7597-4624-9683-263310b85d8a)
👆🏾half logo.

I can see the same problem on these logos too: Godot, Openbugbounty.

But if i use the 'Search bar' for "Discord" it shows correctly! ??

I currently still have the issue when using the pkg logo.
On my local, I fixed the problem by changing the SVG href from '#a' to '#discord' to match the 'id' of the SVG (see snippy above)

**Comment by shinokada** [comment]
Thanks for the update.
It seems that the new version was not reflected on the dist dir.
Please try v1.0.6 and let me know.

This is on the REPL:

https://svelte.dev/repl/13412dd4129d4c76a0764f47470a5043?version=4.2.18

**Comment by hgoona** [comment]
@shinokada Ok that Discord logo works now, but suddenly the BG fill color (white) is now appearing 😬 >>> 
![image](https://github.com/shinokada/svelte-supertiny/assets/30910108/12c5f103-f01a-4587-a5c8-13a11c7a9d8f)
I was previously using the logos like this, and it was working correctly, so I'm not sure what's causing this new issue:
`<Discord fill="none" size="30" pointer-events="none" tabindex="-1" />`

**Comment by shinokada** [comment]
Do you want to remove the white background?

**Comment by hgoona** [comment]
yeah - previously this worked `<Discord fill="none" size="30" />`

**Comment by shinokada** [comment]
Please try v1.0.7 and let me know.

**Comment by hgoona** [comment]
Perfect 💪🏾
